// <auto-generated />
namespace vinodsharma.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class amountgiven : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(amountgiven));
        
        string IMigrationMetadata.Id
        {
            get { return "201802170751411_amountgiven"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
